### ISSUE TITLE
MemoryError on run_PLE.py example

### ISSUE THREAD

**Issue by speedyg0nz** [VinF/deer#46]
Hi, I tried running the PLE example on a simple pygame I came up with but encountered the following error. Would appreciate some guidance here on how to overcome the error. Thanks.

> Traceback (most recent call last):
>   File "run_PLE.py", line 190, in <module>
>     agent.run(parameters.epochs, parameters.steps_per_epoch)
>   File "C:\Users\speedy\Anaconda3\lib\site-packages\deer-0.3-py3.5.egg\deer\agent.py", line 282, in run
>   File "C:\Users\speedy\Anaconda3\lib\site-packages\deer-0.3-py3.5.egg\deer\experiment\base_controllers.py", line 346, in onEpochEnd
>   File "C:\Users\speedy\Anaconda3\lib\site-packages\deer-0.3-py3.5.egg\deer\agent.py", line 173, in startMode
>   File "C:\Users\speedy\Anaconda3\lib\site-packages\deer-0.3-py3.5.egg\deer\agent.py", line 434, in __init__
>   File "C:\Users\speedy\Anaconda3\lib\site-packages\deer-0.3-py3.5.egg\deer\agent.py", line 676, in __init__
> MemoryError

**Comment by speedyg0nz** [comment]
Appears to be an issue with the STEP_PER_EPOCH parameter.
