### ISSUE TITLE
MG_two_storages

### ISSUE THREAD

**Issue by joyandeh** [VinF/deer#89]
Hi dear Vincent,
Thank you very much for your work, it is very helpful.  I tried to run MG_two_storages that I realized an error occur as follow, in FindBestController. Does it need any configuration before run?

Best regards,
EJ
"Average (on the epoch) training loss: 0.9318450183311346
Episode average V value: 0
epoch 1:
Learning rate: 0.0002
Discount factor: 0.9
Epsilon: 0.9987931999999653
Best neural net obtained after 1 epochs, with validation score -78.40202677778416
Traceback (most recent call last):
  File "run_MG_two_storages.py", line 194, in <module>
    agent.run(parameters.epochs, parameters.steps_per_epoch)
  File "/usr/local/lib/python3.7/dist-packages/deer/agent.py", line 269, in run
    self._run_train(n_epochs, epoch_length)
  File "/usr/local/lib/python3.7/dist-packages/deer/agent.py", line 296, in _run_train
    for c in self._controllers: c.onEpochEnd(self)
  File "/usr/local/lib/python3.7/dist-packages/deer/experiment/base_controllers.py", line 338, in onEpochEnd
    agent._run_non_train(n_epochs=1, epoch_length=self._epoch_length)
  File "/usr/local/lib/python3.7/dist-packages/deer/agent.py", line 324, in _run_non_train
    for c in self._controllers: c.onEnd(self)
  File "/usr/local/lib/python3.7/dist-packages/deer/experiment/base_controllers.py", line 558, in onEnd
    print("Test score of this neural net: {}".format(self._testScores[bestIndex]))
IndexError: list index out of range"

**Comment by VinF** [comment]
Hi,

Thanks for reaching out (and sorry for the late answer).

I think you are using a slightly old version of the MG_two_storage environment where, for a short period of time, there was a bug. Can you make sure that you have the last version of the library (https://deer.readthedocs.io/en/0.4.1/user/installation.html#developer-install-instructions) and the last version of the MG_two_storage environment? I've just tested it on my side and it works fine on my side. Please let me know if there is any problem remaining.

Best regards,
Vincent
